version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-config:/opt/jboss/keycloak/config
    command: ["start-dev"]

  cronjob:
    build: .
    volumes:
      - ./add_users.sh:/opt/jboss/tools/add_users.sh
      - ./users.json:/opt/jboss/tools/users.json
    depends_on:
      - keycloak
    entrypoint: ["sh", "-c", "crontab /etc/cron.d/my-cron && tail -f /var/log/cron.log"]